export const NEWPLUGINXXXX_GET__READ = "NEWPLUGINXXXX_GET__READ"
export const NEWPLUGINXXXX_GET__READ_SUCCEEDED =
  "NEWPLUGINXXXX_GET__READ_SUCCEEDED"
export const NEWPLUGINXXXX_GET__READ_FAILED = "NEWPLUGINXXXX_GET__READ_FAILED"
