export const NEWPLUGINXXXX_POST__CREATE = "NEWPLUGINXXXX_POST__CREATE"
export const NEWPLUGINXXXX_POST__CREATE_SUCCEEDED =
  "NEWPLUGINXXXX_POST__CREATE_SUCCEEDED"
export const NEWPLUGINXXXX_POST__CREATE_FAILED =
  "NEWPLUGINXXXX_POST__CREATE_FAILED"
